yml

diff --git a/.github/workflows/ciplan.yml b/.github/workflows/ciplan.yml
--- a/.github/workflows/ciplan.yml
+++ b/.github/workflows/ciplan.yml
@@ -11,6 +11,7 @@ on:
       - develop
     types:
       - closed # Trigger when the PR is closed (merged)
+  workflow_dispatch: # Manually triggerable workflow
 
 permissions:
   contents: write
@@ -94,7 +95,7 @@ jobs:
 
       - name: Run Unit Tests and Capture Test Results
         run: |
-          npm run test -- --coverage --passWithNoTests || { echo "Unit tests failed"; exit 1; }
+          npm run test -- --coverage || { echo "Unit tests failed"; exit 1; }
           mkdir -p test-reports
           if [ -d coverage ]; then
             cp -r coverage/* test-reports/ || echo "No coverage reports found."
