added merge main and develop

diff --git a/.github/workflows/ciplan.yml b/.github/workflows/ciplan.yml
--- a/.github/workflows/ciplan.yml
+++ b/.github/workflows/ciplan.yml
@@ -155,12 +155,13 @@ jobs:
 
       - name: Merge Develop into Release Branch
         run: |
+          git fetch origin
           if git show-ref --quiet refs/heads/release; then
             git checkout release
           else
             git checkout -b release
           fi
-          git merge origin/develop # Change here to specify remote branch
+          git merge origin/develop || { echo "Merge failed"; exit 1; }
           git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/DwightAstrero/BlancTrack.git release
 
   deploy:
@@ -180,6 +181,7 @@ jobs:
 
       - name: Deploy Application to Vercel
         run: vercel --prod --token=$VERCEL_TOKEN --confirm
+
       - name: Set Git user
         run: |
           git config --global user.name "GitHub Action"
@@ -188,9 +190,10 @@ jobs:
       - name: Merge to Main and Develop
         run: |
           echo "Merging to main and develop..."
+          git fetch origin
           git checkout main
-          git merge release
+          git merge origin/release || { echo "Merge failed"; exit 1; }
           git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/DwightAstrero/BlancTrack.git main
           git checkout develop
-          git merge release
+          git merge origin/release || { echo "Merge failed"; exit 1; }
           git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/DwightAstrero/BlancTrack.git develop
