{ echo "Units ..." ....

diff --git a/.github/workflows/ciplan.yml b/.github/workflows/ciplan.yml
--- a/.github/workflows/ciplan.yml
+++ b/.github/workflows/ciplan.yml
@@ -81,7 +81,7 @@ jobs:
 
     - name: Run Unit Tests and Capture Test Results
       run: |
-        npm run test -- --coverage --passWithNoTests || true
+        npm run test -- --coverage --passWithNoTests|| { echo "Unit tests failed"; exit 1; }
         mkdir -p test-reports
         if [ -d coverage ]; then
           cp -r coverage/* test-reports/ || echo "No coverage reports found."
